-- =============================================================================
-- V13__add_product_suspension_and_cancellation_fields.sql
--
-- Acrescenta, a pedido do usuário (21/09/2026 - ver README, seção "Evoluções
-- pedidas"):
--   * T_PRODUCT.SUSPENSION_STATUS: FK lógica para T_DOMAIN_PRODUCT_SUSPENSION_STATUS
--     (V12) - sempre "1 - Adimplente" na criação (não existe, hoje, nenhum
--     fluxo que venda um produto já inadimplente).
--   * T_PRODUCT.CANCELLATION_CHANNEL / CANCELLATION_EFC_DT / CANCELLATION_STATUS /
--     CANCELLATION_DESCRIPTION / AUTO_CANCEL_SCH_B: detalham o MESMO evento
--     que CANCELLATION_REQ_DT/CANCELLATION_SCH_DT (V9) já registrava - a
--     diferença é que V9 só guardava "quando", e estas 5 colunas novas
--     guardam "quem pediu, por qual canal, com qual status e por que". Ver
--     ProductService.persistProducts: reaproveita EXATAMENTE a mesma
--     condição booleana já usada para preencher CANCELLATION_REQ_DT/
--     CANCELLATION_SCH_DT (feature toggle AUTOMATIC_SCHEDULE_CANCEL_FOR_ONE_SHOT
--     ligada E produto ONESHOT com isExpiriationService=true), então as duas
--     "famílias" de coluna nascem e mudam sempre juntas, nunca em
--     dessincronia.
--
-- BACKFILL sem exigir reset de banco: assim como DISABLE_BILLING_B (V9) foi
-- calculada a partir de TYPE (já existente na própria linha), aqui as 3
-- colunas NOT NULL abaixo são calculadas a partir de CANCELLATION_REQ_DT
-- (também já existente, desde V9): CANCELLATION_REQ_DT IS NULL identifica,
-- sem ambiguidade, exatamente o mesmo "cenário 1" (nenhum cancelamento
-- agendado) descrito no pedido do usuário - o "cenário 2" é o caso oposto.
-- =============================================================================

ALTER TABLE T_PRODUCT
    ADD COLUMN SUSPENSION_STATUS      INT NULL,
    ADD COLUMN CANCELLATION_CHANNEL   VARCHAR(50) NULL,
    ADD COLUMN CANCELLATION_EFC_DT    BIGINT NULL,
    ADD COLUMN CANCELLATION_STATUS    INT NULL,
    ADD COLUMN CANCELLATION_DESCRIPTION VARCHAR(500) NULL,
    ADD COLUMN AUTO_CANCEL_SCH_B      CHAR(1) NULL;

-- "Cenário 1" (sem agendamento): SUSPENSION_STATUS=1, CANCELLATION_CHANNEL=NULL,
-- CANCELLATION_STATUS=1, CANCELLATION_DESCRIPTION=NULL, AUTO_CANCEL_SCH_B=0.
UPDATE T_PRODUCT
SET SUSPENSION_STATUS = 1,
    CANCELLATION_CHANNEL = NULL,
    CANCELLATION_STATUS = 1,
    CANCELLATION_DESCRIPTION = NULL,
    AUTO_CANCEL_SCH_B = '0'
WHERE CANCELLATION_REQ_DT IS NULL;

-- "Cenário 2" (cancelamento agendado): SUSPENSION_STATUS=1, CANCELLATION_CHANNEL=BRS,
-- CANCELLATION_STATUS=2, CANCELLATION_DESCRIPTION=texto fixo, AUTO_CANCEL_SCH_B=1.
UPDATE T_PRODUCT
SET SUSPENSION_STATUS = 1,
    CANCELLATION_CHANNEL = 'BRS',
    CANCELLATION_STATUS = 2,
    CANCELLATION_DESCRIPTION = 'Agendamento automatico por ser produto cm servico sem recorrencia',
    AUTO_CANCEL_SCH_B = '1'
WHERE CANCELLATION_REQ_DT IS NOT NULL;

-- CANCELLATION_EFC_DT nasce sempre NULL em ambos os cenários (só é
-- preenchida quando o cancelamento é de fato EFETIVADO - fora do escopo
-- desta v1, igual já registrado para T_BILL.PAYMENT_DT em V6) - por isso
-- fica de fora do UPDATE acima e continua NULLABLE (não entra no MODIFY
-- NOT NULL abaixo).

ALTER TABLE T_PRODUCT
    MODIFY COLUMN SUSPENSION_STATUS INT NOT NULL,
    MODIFY COLUMN CANCELLATION_STATUS INT NOT NULL,
    MODIFY COLUMN AUTO_CANCEL_SCH_B CHAR(1) NOT NULL;

-- Tabela de auditoria + triggers, sincronizadas com a nova estrutura (ver
-- comentário equivalente em V5__add_product_account_id.sql). As 6 colunas
-- nascem NULLABLE em T_PRODUCT_AU mesmo 3 delas sendo NOT NULL na tabela
-- original - mesmo padrão já usado para DISABLE_BILLING_B em V9.
ALTER TABLE T_PRODUCT_AU
    ADD COLUMN SUSPENSION_STATUS      INT NULL,
    ADD COLUMN CANCELLATION_CHANNEL   VARCHAR(50) NULL,
    ADD COLUMN CANCELLATION_EFC_DT    BIGINT NULL,
    ADD COLUMN CANCELLATION_STATUS    INT NULL,
    ADD COLUMN CANCELLATION_DESCRIPTION VARCHAR(500) NULL,
    ADD COLUMN AUTO_CANCEL_SCH_B      CHAR(1) NULL;

DROP TRIGGER TRG_T_PRODUCT_AU_UPD;
DROP TRIGGER TRG_T_PRODUCT_AU_DEL;

DELIMITER $$
CREATE TRIGGER TRG_T_PRODUCT_AU_UPD
    BEFORE UPDATE ON T_PRODUCT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PRODUCT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, PRODUCT_ID, NAME, TYPE, EXP_SERV_B, RECURRENCE_FREQUENCY, VALUE, CURRENCY, TRIAL_B, TRIAL_DAYS, ASSET_ID, NEXT_BILL_DT, FUTURE_BILL_DT, CYCLE_START_DT, CYCLE_END_DT, DEFAULT_PAYMENT_ID, CHANNEL, TRANSACTION_DT, STATUS, DISABLE_BILLING_B, CANCELLATION_REQ_DT, CANCELLATION_SCH_DT, SUSPENSION_STATUS, CANCELLATION_CHANNEL, CANCELLATION_EFC_DT, CANCELLATION_STATUS, CANCELLATION_DESCRIPTION, AUTO_CANCEL_SCH_B)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.PRODUCT_ID, OLD.NAME, OLD.TYPE, OLD.EXP_SERV_B, OLD.RECURRENCE_FREQUENCY, OLD.VALUE, OLD.CURRENCY, OLD.TRIAL_B, OLD.TRIAL_DAYS, OLD.ASSET_ID, OLD.NEXT_BILL_DT, OLD.FUTURE_BILL_DT, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DEFAULT_PAYMENT_ID, OLD.CHANNEL, OLD.TRANSACTION_DT, OLD.STATUS, OLD.DISABLE_BILLING_B, OLD.CANCELLATION_REQ_DT, OLD.CANCELLATION_SCH_DT, OLD.SUSPENSION_STATUS, OLD.CANCELLATION_CHANNEL, OLD.CANCELLATION_EFC_DT, OLD.CANCELLATION_STATUS, OLD.CANCELLATION_DESCRIPTION, OLD.AUTO_CANCEL_SCH_B);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_PRODUCT_AU_DEL
    BEFORE DELETE ON T_PRODUCT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PRODUCT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, PRODUCT_ID, NAME, TYPE, EXP_SERV_B, RECURRENCE_FREQUENCY, VALUE, CURRENCY, TRIAL_B, TRIAL_DAYS, ASSET_ID, NEXT_BILL_DT, FUTURE_BILL_DT, CYCLE_START_DT, CYCLE_END_DT, DEFAULT_PAYMENT_ID, CHANNEL, TRANSACTION_DT, STATUS, DISABLE_BILLING_B, CANCELLATION_REQ_DT, CANCELLATION_SCH_DT, SUSPENSION_STATUS, CANCELLATION_CHANNEL, CANCELLATION_EFC_DT, CANCELLATION_STATUS, CANCELLATION_DESCRIPTION, AUTO_CANCEL_SCH_B)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.PRODUCT_ID, OLD.NAME, OLD.TYPE, OLD.EXP_SERV_B, OLD.RECURRENCE_FREQUENCY, OLD.VALUE, OLD.CURRENCY, OLD.TRIAL_B, OLD.TRIAL_DAYS, OLD.ASSET_ID, OLD.NEXT_BILL_DT, OLD.FUTURE_BILL_DT, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DEFAULT_PAYMENT_ID, OLD.CHANNEL, OLD.TRANSACTION_DT, OLD.STATUS, OLD.DISABLE_BILLING_B, OLD.CANCELLATION_REQ_DT, OLD.CANCELLATION_SCH_DT, OLD.SUSPENSION_STATUS, OLD.CANCELLATION_CHANNEL, OLD.CANCELLATION_EFC_DT, OLD.CANCELLATION_STATUS, OLD.CANCELLATION_DESCRIPTION, OLD.AUTO_CANCEL_SCH_B);
END$$
DELIMITER ;
