-- =============================================================================
-- V14__add_bill_balance_and_refund_fields.sql
--
-- Acrescenta, a pedido do usuário (21/09/2026 - ver README, seção "Evoluções
-- pedidas"):
--   * T_BILL.BALANCE_VALUE: valor em aberto (não pago) da fatura - mesmos
--     moldes de CHARGED_VALUE (DECIMAL(14,2)).
--   * T_BILL.REFUND_VALUE: valor já estornado ao assinante - mesmos moldes.
--   * T_BILL.REFUND_STATUS: FK lógica para T_DOMAIN_BILL_REFUND_STATUS (V12).
--
-- Regra do usuário: "Todas as faturas devem gerar as seguintes informações
-- nos campos novos: BALANCE_VALUE=0, REFUND_VALUE=0, REFUND_STATUS=1" - ou
-- seja, ao contrário de V13 (onde o valor dependia de outra coluna já
-- existente), aqui o valor é o MESMO para toda fatura, tornando o backfill
-- ainda mais simples (nenhum CASE necessário) - mesmo padrão de segurança
-- de 3 passos (ADD COLUMN NULL -> UPDATE -> MODIFY NOT NULL) por precaução,
-- já que T_BILL pode ter linhas de testes anteriores.
-- =============================================================================

ALTER TABLE T_BILL
    ADD COLUMN BALANCE_VALUE DECIMAL(14,2) NULL,
    ADD COLUMN REFUND_VALUE  DECIMAL(14,2) NULL,
    ADD COLUMN REFUND_STATUS INT NULL;

UPDATE T_BILL
SET BALANCE_VALUE = 0,
    REFUND_VALUE = 0,
    REFUND_STATUS = 1;

ALTER TABLE T_BILL
    MODIFY COLUMN BALANCE_VALUE DECIMAL(14,2) NOT NULL,
    MODIFY COLUMN REFUND_VALUE DECIMAL(14,2) NOT NULL,
    MODIFY COLUMN REFUND_STATUS INT NOT NULL;

-- Tabela de auditoria + triggers, sincronizadas com a nova estrutura (ver
-- comentário equivalente em V6__add_bill_cycle_and_payment_dates.sql).
ALTER TABLE T_BILL_AU
    ADD COLUMN BALANCE_VALUE DECIMAL(14,2) NULL,
    ADD COLUMN REFUND_VALUE  DECIMAL(14,2) NULL,
    ADD COLUMN REFUND_STATUS INT NULL;

DROP TRIGGER TRG_T_BILL_AU_UPD;
DROP TRIGGER TRG_T_BILL_AU_DEL;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_AU_UPD
    BEFORE UPDATE ON T_BILL
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, CODE_ID, PRODUCT_ID, PAYMENT_ID, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, CHARGED_VALUE, CURRENCY, TRANSACTION_ID, INSTALLMENTS, PROVIDER, PAYMENT_METHOD, STATUS, BILL_TYPE, CYCLE_START_DT, CYCLE_END_DT, DUE_DT, PAYMENT_DT, BALANCE_VALUE, REFUND_VALUE, REFUND_STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.CODE_ID, OLD.PRODUCT_ID, OLD.PAYMENT_ID, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.CHARGED_VALUE, OLD.CURRENCY, OLD.TRANSACTION_ID, OLD.INSTALLMENTS, OLD.PROVIDER, OLD.PAYMENT_METHOD, OLD.STATUS, OLD.BILL_TYPE, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DUE_DT, OLD.PAYMENT_DT, OLD.BALANCE_VALUE, OLD.REFUND_VALUE, OLD.REFUND_STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_AU_DEL
    BEFORE DELETE ON T_BILL
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, CODE_ID, PRODUCT_ID, PAYMENT_ID, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, CHARGED_VALUE, CURRENCY, TRANSACTION_ID, INSTALLMENTS, PROVIDER, PAYMENT_METHOD, STATUS, BILL_TYPE, CYCLE_START_DT, CYCLE_END_DT, DUE_DT, PAYMENT_DT, BALANCE_VALUE, REFUND_VALUE, REFUND_STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.CODE_ID, OLD.PRODUCT_ID, OLD.PAYMENT_ID, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.CHARGED_VALUE, OLD.CURRENCY, OLD.TRANSACTION_ID, OLD.INSTALLMENTS, OLD.PROVIDER, OLD.PAYMENT_METHOD, OLD.STATUS, OLD.BILL_TYPE, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DUE_DT, OLD.PAYMENT_DT, OLD.BALANCE_VALUE, OLD.REFUND_VALUE, OLD.REFUND_STATUS);
END$$
DELIMITER ;
