-- =============================================================================
-- V3__create_audit_infrastructure.sql
--
-- Cria, para cada tabela elegivel (todas as tabelas de aplicacao, exceto as
-- de dominio - instrucao 4 do enunciado):
--   1) a tabela de auditoria correspondente, com sufixo "_AU", com a MESMA
--      estrutura da tabela original + AU_ID (nova PK autoincremento),
--      AUDIT_DT (data de insercao do registro de auditoria) e COMMAND
--      ('UPDATE' ou 'DELETE'). O campo ID original deixa de ser PK na
--      tabela _AU (pode se repetir, pois um mesmo registro pode ser
--      alterado/excluido varias vezes ao longo do tempo).
--   2) duas triggers BEFORE UPDATE e BEFORE DELETE, que gravam a FOTOGRAFIA
--      do registro ANTES da alteracao/exclusao na tabela _AU.
--
-- AUDIT_DT usa CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), que produz o
-- epoch em milissegundos (mesma convencao usada em toda a base - instrucao 1).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Auditoria de T_LOG
-- -----------------------------------------------------------------------------
CREATE TABLE T_LOG_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    PROTOCOL            VARCHAR(100) NOT NULL,
    RESULT              VARCHAR(20) NOT NULL,
    CODE                VARCHAR(10) NOT NULL,
    REASON              VARCHAR(500) NOT NULL,
    -- Mesmo motivo da tabela original T_LOG (ver comentário em
    -- V2__create_application_schema.sql): VARCHAR(16000) em utf8mb4 estoura
    -- o limite de 65.535 bytes por linha do MySQL/InnoDB (erro 1118 "Row
    -- size too large"). TEXT resolve pelo mesmo motivo: fica armazenado
    -- fora da página principal da linha e não conta para esse limite.
    INPUT               TEXT NOT NULL,
    OUTPUT              TEXT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_LOG_AU_UPD
    BEFORE UPDATE ON T_LOG
    FOR EACH ROW
BEGIN
    INSERT INTO T_LOG_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PROTOCOL, RESULT, CODE, REASON, INPUT, OUTPUT)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PROTOCOL, OLD.RESULT, OLD.CODE, OLD.REASON, OLD.INPUT, OLD.OUTPUT);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_LOG_AU_DEL
    BEFORE DELETE ON T_LOG
    FOR EACH ROW
BEGIN
    INSERT INTO T_LOG_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PROTOCOL, RESULT, CODE, REASON, INPUT, OUTPUT)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PROTOCOL, OLD.RESULT, OLD.CODE, OLD.REASON, OLD.INPUT, OLD.OUTPUT);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_ACCOUNT
-- -----------------------------------------------------------------------------
CREATE TABLE T_ACCOUNT_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    NAME                VARCHAR(200) NOT NULL,
    EXTERNAL_ID         VARCHAR(100) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_AU_UPD
    BEFORE UPDATE ON T_ACCOUNT
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, NAME, EXTERNAL_ID, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.NAME, OLD.EXTERNAL_ID, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_AU_DEL
    BEFORE DELETE ON T_ACCOUNT
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, NAME, EXTERNAL_ID, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.NAME, OLD.EXTERNAL_ID, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_ACCOUNT_DOCUMENT
-- -----------------------------------------------------------------------------
CREATE TABLE T_ACCOUNT_DOCUMENT_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    ACCOUNT_ID          BIGINT NOT NULL,
    TYPE                VARCHAR(20) NOT NULL,
    DESCRIPTION         VARCHAR(200),
    VALUE               VARCHAR(100) NOT NULL,
    COUNTRY             CHAR(2) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_DOCUMENT_AU_UPD
    BEFORE UPDATE ON T_ACCOUNT_DOCUMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_DOCUMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, TYPE, DESCRIPTION, VALUE, COUNTRY, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.TYPE, OLD.DESCRIPTION, OLD.VALUE, OLD.COUNTRY, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_DOCUMENT_AU_DEL
    BEFORE DELETE ON T_ACCOUNT_DOCUMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_DOCUMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, TYPE, DESCRIPTION, VALUE, COUNTRY, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.TYPE, OLD.DESCRIPTION, OLD.VALUE, OLD.COUNTRY, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_ACCOUNT_ADDRESS
-- -----------------------------------------------------------------------------
CREATE TABLE T_ACCOUNT_ADDRESS_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    ACCOUNT_ID          BIGINT NOT NULL,
    TYPE                VARCHAR(20) NOT NULL,
    DESCRIPTION         VARCHAR(200) NOT NULL,
    ADDRESS_NAME        VARCHAR(200) NOT NULL,
    NUMBER              VARCHAR(20) NOT NULL,
    COMPLEMENT          VARCHAR(200),
    ZIP_CODE            VARCHAR(20) NOT NULL,
    COUNTRY             CHAR(2) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_ADDRESS_AU_UPD
    BEFORE UPDATE ON T_ACCOUNT_ADDRESS
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_ADDRESS_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, TYPE, DESCRIPTION, ADDRESS_NAME, NUMBER, COMPLEMENT, ZIP_CODE, COUNTRY, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.TYPE, OLD.DESCRIPTION, OLD.ADDRESS_NAME, OLD.NUMBER, OLD.COMPLEMENT, OLD.ZIP_CODE, OLD.COUNTRY, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_ADDRESS_AU_DEL
    BEFORE DELETE ON T_ACCOUNT_ADDRESS
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_ADDRESS_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, TYPE, DESCRIPTION, ADDRESS_NAME, NUMBER, COMPLEMENT, ZIP_CODE, COUNTRY, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.TYPE, OLD.DESCRIPTION, OLD.ADDRESS_NAME, OLD.NUMBER, OLD.COMPLEMENT, OLD.ZIP_CODE, OLD.COUNTRY, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_ACCOUNT_PHONE
-- -----------------------------------------------------------------------------
CREATE TABLE T_ACCOUNT_PHONE_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    ACCOUNT_ID          BIGINT NOT NULL,
    NUMBER              VARCHAR(20) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_PHONE_AU_UPD
    BEFORE UPDATE ON T_ACCOUNT_PHONE
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_PHONE_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, NUMBER, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.NUMBER, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_ACCOUNT_PHONE_AU_DEL
    BEFORE DELETE ON T_ACCOUNT_PHONE
    FOR EACH ROW
BEGIN
    INSERT INTO T_ACCOUNT_PHONE_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, NUMBER, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.NUMBER, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_PRODUCT
-- -----------------------------------------------------------------------------
CREATE TABLE T_PRODUCT_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    PRODUCT_ID          VARCHAR(100) NOT NULL,
    NAME                VARCHAR(200) NOT NULL,
    TYPE                VARCHAR(20) NOT NULL,
    EXP_SERV_B          CHAR(1) NOT NULL,
    RECURRENCE_FREQUENCY VARCHAR(20),
    VALUE               DECIMAL(14,2) NOT NULL,
    CURRENCY            CHAR(3) NOT NULL,
    TRIAL_B             CHAR(1) NOT NULL,
    TRIAL_DAYS          INT,
    ASSET_ID            VARCHAR(100),
    NEXT_BILL_DT        BIGINT,
    FUTURE_BILL_DT      BIGINT,
    CYCLE_START_DT      BIGINT NOT NULL,
    CYCLE_END_DT        BIGINT,
    DEFAULT_PAYMENT_ID  VARCHAR(100),
    CHANNEL             VARCHAR(50) NOT NULL,
    TRANSACTION_DT      BIGINT NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_PRODUCT_AU_UPD
    BEFORE UPDATE ON T_PRODUCT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PRODUCT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PRODUCT_ID, NAME, TYPE, EXP_SERV_B, RECURRENCE_FREQUENCY, VALUE, CURRENCY, TRIAL_B, TRIAL_DAYS, ASSET_ID, NEXT_BILL_DT, FUTURE_BILL_DT, CYCLE_START_DT, CYCLE_END_DT, DEFAULT_PAYMENT_ID, CHANNEL, TRANSACTION_DT, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PRODUCT_ID, OLD.NAME, OLD.TYPE, OLD.EXP_SERV_B, OLD.RECURRENCE_FREQUENCY, OLD.VALUE, OLD.CURRENCY, OLD.TRIAL_B, OLD.TRIAL_DAYS, OLD.ASSET_ID, OLD.NEXT_BILL_DT, OLD.FUTURE_BILL_DT, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DEFAULT_PAYMENT_ID, OLD.CHANNEL, OLD.TRANSACTION_DT, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_PRODUCT_AU_DEL
    BEFORE DELETE ON T_PRODUCT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PRODUCT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PRODUCT_ID, NAME, TYPE, EXP_SERV_B, RECURRENCE_FREQUENCY, VALUE, CURRENCY, TRIAL_B, TRIAL_DAYS, ASSET_ID, NEXT_BILL_DT, FUTURE_BILL_DT, CYCLE_START_DT, CYCLE_END_DT, DEFAULT_PAYMENT_ID, CHANNEL, TRANSACTION_DT, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PRODUCT_ID, OLD.NAME, OLD.TYPE, OLD.EXP_SERV_B, OLD.RECURRENCE_FREQUENCY, OLD.VALUE, OLD.CURRENCY, OLD.TRIAL_B, OLD.TRIAL_DAYS, OLD.ASSET_ID, OLD.NEXT_BILL_DT, OLD.FUTURE_BILL_DT, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DEFAULT_PAYMENT_ID, OLD.CHANNEL, OLD.TRANSACTION_DT, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_DISCOUNT
-- -----------------------------------------------------------------------------
CREATE TABLE T_DISCOUNT_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    START_DT            BIGINT NOT NULL,
    END_DT              BIGINT NOT NULL,
    VALUE               DECIMAL(14,2) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_DISCOUNT_AU_UPD
    BEFORE UPDATE ON T_DISCOUNT
    FOR EACH ROW
BEGIN
    INSERT INTO T_DISCOUNT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PRODUCT_ID, START_DT, END_DT, VALUE, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PRODUCT_ID, OLD.START_DT, OLD.END_DT, OLD.VALUE, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_DISCOUNT_AU_DEL
    BEFORE DELETE ON T_DISCOUNT
    FOR EACH ROW
BEGIN
    INSERT INTO T_DISCOUNT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PRODUCT_ID, START_DT, END_DT, VALUE, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PRODUCT_ID, OLD.START_DT, OLD.END_DT, OLD.VALUE, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_PAYMENT
-- -----------------------------------------------------------------------------
CREATE TABLE T_PAYMENT_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    ACCOUNT_ID          BIGINT NOT NULL,
    METHOD              VARCHAR(20) NOT NULL,
    ISSUER              VARCHAR(100),
    CARD_NUMBER         VARCHAR(50),
    EXPIRATION          VARCHAR(5),
    MULTIPLE_B          CHAR(1),
    DEFAULT_B           CHAR(1) NOT NULL,
    INSTALLMENTS        VARCHAR(5) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_PAYMENT_AU_UPD
    BEFORE UPDATE ON T_PAYMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PAYMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, METHOD, ISSUER, CARD_NUMBER, EXPIRATION, MULTIPLE_B, DEFAULT_B, INSTALLMENTS, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.METHOD, OLD.ISSUER, OLD.CARD_NUMBER, OLD.EXPIRATION, OLD.MULTIPLE_B, OLD.DEFAULT_B, OLD.INSTALLMENTS, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_PAYMENT_AU_DEL
    BEFORE DELETE ON T_PAYMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PAYMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, METHOD, ISSUER, CARD_NUMBER, EXPIRATION, MULTIPLE_B, DEFAULT_B, INSTALLMENTS, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.METHOD, OLD.ISSUER, OLD.CARD_NUMBER, OLD.EXPIRATION, OLD.MULTIPLE_B, OLD.DEFAULT_B, OLD.INSTALLMENTS, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_PAYMENT_TOKEN
-- -----------------------------------------------------------------------------
CREATE TABLE T_PAYMENT_TOKEN_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    PAYMENT_ID          BIGINT NOT NULL,
    NAME                VARCHAR(100) NOT NULL,
    TOKEN               VARCHAR(200) NOT NULL,
    GATEWAY             VARCHAR(100) NOT NULL,
    EXPIRATION_DT       BIGINT,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_PAYMENT_TOKEN_AU_UPD
    BEFORE UPDATE ON T_PAYMENT_TOKEN
    FOR EACH ROW
BEGIN
    INSERT INTO T_PAYMENT_TOKEN_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PAYMENT_ID, NAME, TOKEN, GATEWAY, EXPIRATION_DT, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PAYMENT_ID, OLD.NAME, OLD.TOKEN, OLD.GATEWAY, OLD.EXPIRATION_DT, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_PAYMENT_TOKEN_AU_DEL
    BEFORE DELETE ON T_PAYMENT_TOKEN
    FOR EACH ROW
BEGIN
    INSERT INTO T_PAYMENT_TOKEN_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, PAYMENT_ID, NAME, TOKEN, GATEWAY, EXPIRATION_DT, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.PAYMENT_ID, OLD.NAME, OLD.TOKEN, OLD.GATEWAY, OLD.EXPIRATION_DT, OLD.STATUS);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_BILL
-- -----------------------------------------------------------------------------
CREATE TABLE T_BILL_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    CODE_ID             VARCHAR(100) NOT NULL,
    PRODUCT_ID          BIGINT NOT NULL,
    PAYMENT_ID          BIGINT,
    PRODUCT_VALUE       DECIMAL(14,2) NOT NULL,
    DISCOUNT_VALUE      DECIMAL(14,2) NOT NULL,
    TAX_VALUE           DECIMAL(14,2) NOT NULL,
    CHARGED_VALUE       DECIMAL(14,2) NOT NULL,
    CURRENCY            CHAR(3) NOT NULL,
    TRANSACTION_ID      VARCHAR(100) NOT NULL,
    INSTALLMENTS        VARCHAR(5) NOT NULL,
    PROVIDER            VARCHAR(100) NOT NULL,
    PAYMENT_METHOD      VARCHAR(20) NOT NULL,
    STATUS              INT NOT NULL,
    BILL_TYPE           INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_AU_UPD
    BEFORE UPDATE ON T_BILL
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, CODE_ID, PRODUCT_ID, PAYMENT_ID, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, CHARGED_VALUE, CURRENCY, TRANSACTION_ID, INSTALLMENTS, PROVIDER, PAYMENT_METHOD, STATUS, BILL_TYPE)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.CODE_ID, OLD.PRODUCT_ID, OLD.PAYMENT_ID, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.CHARGED_VALUE, OLD.CURRENCY, OLD.TRANSACTION_ID, OLD.INSTALLMENTS, OLD.PROVIDER, OLD.PAYMENT_METHOD, OLD.STATUS, OLD.BILL_TYPE);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_AU_DEL
    BEFORE DELETE ON T_BILL
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, CODE_ID, PRODUCT_ID, PAYMENT_ID, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, CHARGED_VALUE, CURRENCY, TRANSACTION_ID, INSTALLMENTS, PROVIDER, PAYMENT_METHOD, STATUS, BILL_TYPE)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.CODE_ID, OLD.PRODUCT_ID, OLD.PAYMENT_ID, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.CHARGED_VALUE, OLD.CURRENCY, OLD.TRANSACTION_ID, OLD.INSTALLMENTS, OLD.PROVIDER, OLD.PAYMENT_METHOD, OLD.STATUS, OLD.BILL_TYPE);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_BILL_TAX
-- -----------------------------------------------------------------------------
CREATE TABLE T_BILL_TAX_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    BILL_ID             BIGINT NOT NULL,
    NAME                VARCHAR(50) NOT NULL,
    VALUE               DECIMAL(14,2) NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_TAX_AU_UPD
    BEFORE UPDATE ON T_BILL_TAX
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_TAX_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, BILL_ID, NAME, VALUE)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.BILL_ID, OLD.NAME, OLD.VALUE);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_TAX_AU_DEL
    BEFORE DELETE ON T_BILL_TAX
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_TAX_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, BILL_ID, NAME, VALUE)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.BILL_ID, OLD.NAME, OLD.VALUE);
END$$
DELIMITER ;

-- -----------------------------------------------------------------------------
-- Auditoria de T_BILL_INSTALLMENT
-- -----------------------------------------------------------------------------
CREATE TABLE T_BILL_INSTALLMENT_AU
(
    AU_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    AUDIT_DT    BIGINT      NOT NULL,
    COMMAND     VARCHAR(10) NOT NULL,
    ID                  BIGINT,
    CREATED_DT          BIGINT NOT NULL,
    MODIFIED_DT         BIGINT NOT NULL,
    BILL_ID             BIGINT NOT NULL,
    INSTALLMENT         INT NOT NULL,
    TOTAL_INSTALLMENT   INT NOT NULL,
    PRODUCT_VALUE       DECIMAL(14,2) NOT NULL,
    DISCOUNT_VALUE      DECIMAL(14,2) NOT NULL,
    TAX_VALUE           DECIMAL(14,2) NOT NULL,
    STATUS              INT NOT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_INSTALLMENT_AU_UPD
    BEFORE UPDATE ON T_BILL_INSTALLMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_INSTALLMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, BILL_ID, INSTALLMENT, TOTAL_INSTALLMENT, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.BILL_ID, OLD.INSTALLMENT, OLD.TOTAL_INSTALLMENT, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.STATUS);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_INSTALLMENT_AU_DEL
    BEFORE DELETE ON T_BILL_INSTALLMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_INSTALLMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, BILL_ID, INSTALLMENT, TOTAL_INSTALLMENT, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, STATUS)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.BILL_ID, OLD.INSTALLMENT, OLD.TOTAL_INSTALLMENT, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.STATUS);
END$$
DELIMITER ;
