-- =============================================================================
-- V7__add_bill_installment_payment_date.sql
--
-- Acrescenta T_BILL_INSTALLMENT.PAYMENT_DT: data em que o repasse daquela
-- parcela específica foi efetivado. Mesma lógica de T_BILL.PAYMENT_DT (ver
-- V6__add_bill_cycle_and_payment_dates.sql) - sempre NULL quando a parcela
-- é criada pelo fluxo de "POST /api/v1/purchases", a ser preenchido
-- futuramente por um processo de liquidação de parcelas.
-- =============================================================================

ALTER TABLE T_BILL_INSTALLMENT
    ADD COLUMN PAYMENT_DT BIGINT NULL;

-- Tabela de auditoria + triggers, sincronizadas com a nova estrutura.
ALTER TABLE T_BILL_INSTALLMENT_AU
    ADD COLUMN PAYMENT_DT BIGINT NULL;

DROP TRIGGER TRG_T_BILL_INSTALLMENT_AU_UPD;
DROP TRIGGER TRG_T_BILL_INSTALLMENT_AU_DEL;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_INSTALLMENT_AU_UPD
    BEFORE UPDATE ON T_BILL_INSTALLMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_INSTALLMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, BILL_ID, INSTALLMENT, TOTAL_INSTALLMENT, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, STATUS, PAYMENT_DT)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.BILL_ID, OLD.INSTALLMENT, OLD.TOTAL_INSTALLMENT, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.STATUS, OLD.PAYMENT_DT);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_BILL_INSTALLMENT_AU_DEL
    BEFORE DELETE ON T_BILL_INSTALLMENT
    FOR EACH ROW
BEGIN
    INSERT INTO T_BILL_INSTALLMENT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, BILL_ID, INSTALLMENT, TOTAL_INSTALLMENT, PRODUCT_VALUE, DISCOUNT_VALUE, TAX_VALUE, STATUS, PAYMENT_DT)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.BILL_ID, OLD.INSTALLMENT, OLD.TOTAL_INSTALLMENT, OLD.PRODUCT_VALUE, OLD.DISCOUNT_VALUE, OLD.TAX_VALUE, OLD.STATUS, OLD.PAYMENT_DT);
END$$
DELIMITER ;
