-- =============================================================================
-- V9__add_product_disable_billing_and_cancellation.sql
--
-- Acrescenta, a pedido do usuário (17/09/2026 - ver README, seção "Evoluções
-- pedidas"):
--   * T_PRODUCT.DISABLE_BILLING_B: sempre '1' quando TYPE = 'ONESHOT', sempre
--     '0' nos demais casos. Regra puramente derivada de outra coluna já
--     existente na própria linha (TYPE) - por isso, diferente de V5/V6/V8,
--     NÃO precisamos pedir para o usuário resetar o banco: conseguimos
--     calcular o valor correto de qualquer linha já existente com um simples
--     UPDATE, e só então tornar a coluna NOT NULL. Este é o padrão "seguro"
--     de 3 passos já usado em V4 (ADD COLUMN NULL -> UPDATE com a regra ->
--     MODIFY NOT NULL), aqui reaproveitado com uma regra derivada em vez de
--     uma tabela de mapeamento fixa.
--   * T_PRODUCT.CANCELLATION_REQ_DT / CANCELLATION_SCH_DT: ambas sempre
--     NULLABLE (ver regra completa em V10, associada ao feature toggle
--     AUTOMATIC_SCHEDULE_CANCEL_FOR_ONE_SHOT) - não há necessidade de
--     backfill nem de reset de banco para estas duas.
-- =============================================================================

ALTER TABLE T_PRODUCT
    ADD COLUMN DISABLE_BILLING_B CHAR(1) NULL;

UPDATE T_PRODUCT
SET DISABLE_BILLING_B = CASE WHEN TYPE = 'ONESHOT' THEN '1' ELSE '0' END;

ALTER TABLE T_PRODUCT
    MODIFY COLUMN DISABLE_BILLING_B CHAR(1) NOT NULL;

ALTER TABLE T_PRODUCT
    ADD COLUMN CANCELLATION_REQ_DT BIGINT NULL,
    ADD COLUMN CANCELLATION_SCH_DT BIGINT NULL;

-- Tabela de auditoria + triggers, sincronizadas com a nova estrutura (ver
-- comentário equivalente em V5__add_product_account_id.sql). As três colunas
-- nascem NULLABLE em T_PRODUCT_AU mesmo DISABLE_BILLING_B sendo NOT NULL na
-- tabela original - mesmo padrão já usado para ACCOUNT_ID em V5.
ALTER TABLE T_PRODUCT_AU
    ADD COLUMN DISABLE_BILLING_B CHAR(1) NULL,
    ADD COLUMN CANCELLATION_REQ_DT BIGINT NULL,
    ADD COLUMN CANCELLATION_SCH_DT BIGINT NULL;

DROP TRIGGER TRG_T_PRODUCT_AU_UPD;
DROP TRIGGER TRG_T_PRODUCT_AU_DEL;

DELIMITER $$
CREATE TRIGGER TRG_T_PRODUCT_AU_UPD
    BEFORE UPDATE ON T_PRODUCT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PRODUCT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, PRODUCT_ID, NAME, TYPE, EXP_SERV_B, RECURRENCE_FREQUENCY, VALUE, CURRENCY, TRIAL_B, TRIAL_DAYS, ASSET_ID, NEXT_BILL_DT, FUTURE_BILL_DT, CYCLE_START_DT, CYCLE_END_DT, DEFAULT_PAYMENT_ID, CHANNEL, TRANSACTION_DT, STATUS, DISABLE_BILLING_B, CANCELLATION_REQ_DT, CANCELLATION_SCH_DT)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'UPDATE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.PRODUCT_ID, OLD.NAME, OLD.TYPE, OLD.EXP_SERV_B, OLD.RECURRENCE_FREQUENCY, OLD.VALUE, OLD.CURRENCY, OLD.TRIAL_B, OLD.TRIAL_DAYS, OLD.ASSET_ID, OLD.NEXT_BILL_DT, OLD.FUTURE_BILL_DT, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DEFAULT_PAYMENT_ID, OLD.CHANNEL, OLD.TRANSACTION_DT, OLD.STATUS, OLD.DISABLE_BILLING_B, OLD.CANCELLATION_REQ_DT, OLD.CANCELLATION_SCH_DT);
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER TRG_T_PRODUCT_AU_DEL
    BEFORE DELETE ON T_PRODUCT
    FOR EACH ROW
BEGIN
    INSERT INTO T_PRODUCT_AU (AUDIT_DT, COMMAND, ID, CREATED_DT, MODIFIED_DT, ACCOUNT_ID, PRODUCT_ID, NAME, TYPE, EXP_SERV_B, RECURRENCE_FREQUENCY, VALUE, CURRENCY, TRIAL_B, TRIAL_DAYS, ASSET_ID, NEXT_BILL_DT, FUTURE_BILL_DT, CYCLE_START_DT, CYCLE_END_DT, DEFAULT_PAYMENT_ID, CHANNEL, TRANSACTION_DT, STATUS, DISABLE_BILLING_B, CANCELLATION_REQ_DT, CANCELLATION_SCH_DT)
    VALUES (CAST(UNIX_TIMESTAMP(NOW(3)) * 1000 AS UNSIGNED), 'DELETE', OLD.ID, OLD.CREATED_DT, OLD.MODIFIED_DT, OLD.ACCOUNT_ID, OLD.PRODUCT_ID, OLD.NAME, OLD.TYPE, OLD.EXP_SERV_B, OLD.RECURRENCE_FREQUENCY, OLD.VALUE, OLD.CURRENCY, OLD.TRIAL_B, OLD.TRIAL_DAYS, OLD.ASSET_ID, OLD.NEXT_BILL_DT, OLD.FUTURE_BILL_DT, OLD.CYCLE_START_DT, OLD.CYCLE_END_DT, OLD.DEFAULT_PAYMENT_ID, OLD.CHANNEL, OLD.TRANSACTION_DT, OLD.STATUS, OLD.DISABLE_BILLING_B, OLD.CANCELLATION_REQ_DT, OLD.CANCELLATION_SCH_DT);
END$$
DELIMITER ;
